# 高可用注册中心，Eureka Server的高可用就是将自己作为服务向其他服务注册中心注册自己，这样就形成了一组相互注册的服务注册中心，以实现服务清单的相互同步，达到高可用的效果。

# 当设置了多个注册中心以后，服务提供方和消费方还需要在自己的注册中心上加上集群地址,用逗号分割：
#   eureka.client.serviceUrl.defaultZone=http://peer2:8012/eureka/,http://peer1:8012/eureka/
#   如果不想使用peer这种主机名来定义注册中心，也可以使用ip地址的形式，但是需要在配置文件中增加配置参数：eureka.instance.prefer-ip-address=true，改值默认为false

# 注册中心集群2 java -jar spring-cloud-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
server:
  port: 9092
spring:
  application:
    name: eureka-server-peer2
eureka:
  instance:
    hostname: localhost
  client:
  # fetch-registry：表示是否从eureka server获取注册信息，如果是单一节点，不需要同步其他eureka server节点，
  #  则可以设置为false，但此处为集群，应该设置为true，默认为true，可不设置。
  # register-with-eureka：表示是否将自己注册到eureka server，因为要构建集群环境，需要将自己注册到及群众，所以应该开启。默认为true，可不显式设置。
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/