spring:
  application:
    name: spring-cloud-consumer
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    instance-id: spring-cloud-consumer_8085
    prefer-ip-address: true #访问路径可以显示IP地址