eureka:
  client:
    service-url:
#      defaultZone: http://localhost:9091/eureka/,http://localhost:9092/eureka/
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: spring-cloud-provider
server:
  port: 8081
