eureka:
  client:
    service-url:
#    高可用的服务注册中心是集群的，所以需要配置集群地址
#      defaultZone: http://localhost:9091/eureka/,http://localhost:9092/eureka/
      defaultZone: http://localhost:9000/eureka/
  instance:
    instance-id: spring-cloud-provider_8801
    prefer-ip-address: true #访问路径可以显示IP地址
spring:
  application:
    name: spring-cloud-provider
server:
  port: 8081
